### ISSUE TITLE
List of Jokes

### ISSUE THREAD

**Issue by PReichetanz** [PReichetanz/capstone-user-stories#1]
## Value Proposition

**As a**
**I need** ...(describe the goal)
**to be able to** ...(describe the reason)

## Description

Scribble / design or text
<img width="200px" alt="step_1" src="https://user-images.githubusercontent.com/33567019/179001335-374b8780-af86-4b91-aab0-05cdc70f1ed0.png"/>

## Acceptance Criteria

- [x] describe every scenario in detail
- [x] e.g. All Inputs are required, show warning if empty.
- [x] ...

## Tasks

(for developers team)

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...

**Comment by PReichetanz** [comment]
First comment

**Comment by PReichetanz** [comment]
> First comment

@anresa

**Comment by PReichetanz** [comment]
Test to refer to another issue PReichetanz/capstone-project-example-muc-web-22-3#3
